#!/usr/bin/env python2
# -*- coding: UTF-8 -*-
 
import sys
import os
 
n=0
with open('ip.list', 'r') as f:
    for ip in f:
        ip = ip.replace("\n", "")
        if len(ip) > 0:
            with open('/etc/sysconfig/network-scripts/ifcfg-eth0:' + str(n), 'wb') as f:
                text = "\n".join(["DEVICE=eth0:" + str(n),
                    "BOOTPROTO=static",
                    "IPADDR=" + ip,
                    "NETMASK=255.255.255.0"
                    "ONBOOT=yes"])
                f.write(text)
            n += 1
